coverage:
  range: "85...100"

fixes:
  - "/home/travis/build/*/boost-root/boost/::include/boost/"
  - "/home/travis/build/*/boost-root/libs/uuid/::"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
